server:
  port: 9700
spring:
  dubbo:
    application:
      name: gmall-search-service
    registry:
      address: 192.168.10.100:2181
    protocol:
      name: dubbo
    consumer:
      check: false # 不检查消费者
      timeout: 10000
    base-package: com.gmall.service.impl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmall?characterEncoding=UTF-8
    username: root
    password: nl1120
  elasticsearch:
    jest:
      uris: http://192.168.10.100:9200
  redis:
    host: 192.168.10.100
    password: nl1120
    port: 6379
    database: 0

#  level:
#    root: debug

