server:
  port: 9800
  servlet:
    context-path: /cart

spring:
  dubbo:
    application: gmall-cart-web
    consumer:
      check: false
      timeout: 60000
    registry:
      address: 192.168.10.100:2181
      protocol: zookeeper
    base-package: com.gmall.controller
    thymeleaf:
      cache: false #更改后重新rebuild即可，关闭thymeleaf的缓存机制

#logging:
#  level:
#    root: debug
